package Exception;

public class TestFinally {
	Public static void main(String[] args) {
		try {
			int data
		}
	}

}
